### PR TITLE
add dotenv dependency

### LINKED ISSUE #72: Sign In
### Description
User is able to sign in using amazon cognito

### Acceptance Criteria
Screenshot that it works

### PR DESCRIPTION
**Pull request by yanDavid21**
### ℹ️ Issue

Closes #72 

### 📝 Description

Briefly list the changes made to the code:

- Added dot env support
- updated gitignore to exclude idea (non-functional)

### ✔️ Verification

- added a .env file with necessary variables (COGNITO_ISSUER, COGNITO_CLIENT_ID, COGNITO_CLIENT_SECRET)*
- signed in in hosted url at https://outstandinglife.auth.us-east-2.amazoncognito.com/login?client_id=7r52rrovsug54v9domil8lgru2&response_type=code&scope=email+openid+profile&redirect_uri=http://localhost:3000/api/auth/callback/cognito 
- verified we are redirected to our landing page at outstandinglife.org
- verified we have a sign in token/session (see image below)

*these variables can found in aws cognitor, but can message @yanDavid21 @jessicasu77 for more information as well

Provide screenshots of any new components, styling changes, or pages. 

image

### 🏕️ (Optional) Future Work / Notes

Did you notice anything ugly during the course of this ticket? Any bugs, design challenges, or unexpected behavior? Write it down so we can clean it up in a future ticket!

This works for local development. For production, we would need to host our nextjs app on ec2 or similar computing option. Then we would need to generate a new ,env there for the prod cognito client (osl_client_nextjs_prod) with a new callback url in App client settings (again for osl_client_nextjs_prod). Additionally, we need to generate a next_auth_secret for production (and also switch our app in production for production ;) (in dockerfile)).

### CODE REVIEW

**Review by ja0911 — DISMISSED** [review]

**Comment by rymaju** [comment]
My understanding was that environment variables were built into Next via `.env.local` as described here: https://nextjs.org/docs/basic-features/environment-variables

**Comment by yanDavid21** [comment]
> My understanding was that environment variables were built into Next via `.env.local` as described here: https://nextjs.org/docs/basic-features/environment-variables

Thanks for the heads up. Looks like a nonfunctional change, we'll look to refactor this then. @jessicasu77

**Review by thejamielin — COMMENTED** [review]
Looks good so far! @yanDavid21 and @jessicasu77 would you like to make a new ticket for refactoring or just continue working off of this one? I'll wait for the updates to approve then

**Comment by yanDavid21** [comment]
> Looks good so far! @yanDavid21 and @jessicasu77 would you like to make a new ticket for refactoring or just continue working off of this one? I'll wait for the updates to approve then

We'll update this branch. Don't think we should make a new ticket since we're not going to commit these changes.

**Review by thejamielin — COMMENTED** [review]
looks good so far! @jessicasu77 were you able to load outstandinglife.org even with postgres issues? I'm going to get that to work first so that I can see that being signed in leads to  outstandingelife.org , but after that I'll approve!

**Comment by jessicasu77** [comment]
> looks good so far! @jessicasu77 were you able to load outstandinglife.org even with postgres issues? I'm going to get that to work first so that I can see that being signed in leads to outstandingelife.org , but after that I'll approve!

Wasn't able to sign in without fixing the postgres issue

**Review by thejamielin — APPROVED** [review]
looks good to me! you're all set to merge

**Review by adriannaliu — APPROVED** [review]
nice job guys!

**Pull request closed without merging**
