### PR TITLE
about us enhancements

### LINKED ISSUE #43: Front-end: About Us Page
# Purpose
There are some minor changes that need to made to OSL.

# Description
Please update the About Us page with changes marked from the Davids from this [doc ](https://docs.google.com/document/d/1O2HuRZnJbe8Wgx3U5zy11OfPvDkGRgMl/edit?usp=sharing&ouid=105775914785337038980&rtpof=true&sd=true)
- [x] Update "Our Mission and Purpose" section
- [x] Update "The Need" section
- [x] In "Leadership Team": Update Alice Fischer's Bio
- [x] In "Leadership Team": Add Julia Nowak [picture ](https://drive.google.com/file/d/1OkNqOuQ8LlhJpdzdgRahd6Agsm3A3Bnm/view?usp=sharing) and bio

# Acceptance Criteria
- [ ] Please attach of screenshot of updated sections to your PR

### PR DESCRIPTION
**Pull request by jessicasu77**
### ℹ️ Issue

Closes #43

### 📝 Description

Briefly list the changes made to the code:

- Update "Our Mission and Purpose" section
- Update "The Need" section
- In "Leadership Team": Update Alice Fischer's Bio
- In "Leadership Team": Add Julia Nowak picture + bio

### ✔️ Verification
Alice Fischer bio
Screenshot 2022-07-31 at 2 07 11 PM

Julia Nowak picture + bio
Screenshot 2022-07-31 at 2 06 21 PM

Mission and purpose section
Screenshot 2022-07-31 at 2 07 52 PM

Need section
Screenshot 2022-07-31 at 2 08 15 PM

### CODE REVIEW

**Review by al-chang — DISMISSED** [review]
LGTM

**Comment by adriannaliu** [comment]
amazing jess!!!! one small thing, can you add a quotation mark at the end of this sentence please: “LGBT Aging 2025: Strategies for Achieving a Healthy and Thriving LGBT Older Adult Community in Massachusetts” — Need section, 2nd paragraph

**Review by saahilkumar — APPROVED** [review]
Ye looks good other than Adri's small suggestion ^

**Review by adriannaliu — APPROVED** [review]
lgtm 💯

**Review by thejamielin — APPROVED** [review]
lgtm! woot woot great job first PR approved of the summer!

**Pull request merged**
